# Site settings
title: Sohaib Baig
description: ""
url: "" # your GitHub Pages URL will go here, e.g., https://username.github.io
baseurl: "" # if your blog is in a subdirectory, specify it here

# Social links
linkedin_username: sohaibbaig1
github_username: sohaibbg

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - first.txt
  - README.md
